"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.d3api_locator import D3apiLocator
globals()['D3apiLocator'] = D3apiLocator
from openapi_client.model.transport_set_brightness_info import TransportSetBrightnessInfo


class TestTransportSetBrightnessInfo(unittest.TestCase):
    """TransportSetBrightnessInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransportSetBrightnessInfo(self):
        """Test TransportSetBrightnessInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransportSetBrightnessInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
