"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.transport_go_to_time_info import TransportGoToTimeInfo
globals()['TransportGoToTimeInfo'] = TransportGoToTimeInfo
from openapi_client.model.transport_go_to_time_request import TransportGoToTimeRequest


class TestTransportGoToTimeRequest(unittest.TestCase):
    """TransportGoToTimeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransportGoToTimeRequest(self):
        """Test TransportGoToTimeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransportGoToTimeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
