"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.colour_cdl_info import ColourCDLInfo
globals()['ColourCDLInfo'] = ColourCDLInfo
from openapi_client.model.colour_set_cdl_request import ColourSetCDLRequest


class TestColourSetCDLRequest(unittest.TestCase):
    """ColourSetCDLRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColourSetCDLRequest(self):
        """Test ColourSetCDLRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ColourSetCDLRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
