"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cameracalibration_mr_set_info import CameracalibrationMRSetInfo
globals()['CameracalibrationMRSetInfo'] = CameracalibrationMRSetInfo
from openapi_client.model.cameracalibration_list_mr_sets_response import CameracalibrationListMRSetsResponse


class TestCameracalibrationListMRSetsResponse(unittest.TestCase):
    """CameracalibrationListMRSetsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCameracalibrationListMRSetsResponse(self):
        """Test CameracalibrationListMRSetsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CameracalibrationListMRSetsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
