"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cameracalibration_float3 import CameracalibrationFloat3
globals()['CameracalibrationFloat3'] = CameracalibrationFloat3
from openapi_client.model.cameracalibration_observation_info import CameracalibrationObservationInfo


class TestCameracalibrationObservationInfo(unittest.TestCase):
    """CameracalibrationObservationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCameracalibrationObservationInfo(self):
        """Test CameracalibrationObservationInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CameracalibrationObservationInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
