"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.quickcal_api import QuickcalApi  # noqa: E501


class TestQuickcalApi(unittest.TestCase):
    """QuickcalApi unit test stubs"""

    def setUp(self):
        self.api = QuickcalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_quickcal_line_up_current_pose(self):
        """Test case for quickcal_line_up_current_pose

        Lineup the current pose for the selected projector according to the selected reference points  # noqa: E501
        """
        pass

    def test_quickcal_list_reference_points(self):
        """Test case for quickcal_list_reference_points

        Returns a list of all reference points  # noqa: E501
        """
        pass

    def test_quickcal_reset_line_up(self):
        """Test case for quickcal_reset_line_up

        Resets the lineup of the selected projector  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
