"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.renderstream_pool_info import RenderstreamPoolInfo
from openapi_client.model.rpc_status import RpcStatus
globals()['RenderstreamPoolInfo'] = RenderstreamPoolInfo
globals()['RpcStatus'] = RpcStatus
from openapi_client.model.renderstream_get_pools_response import RenderstreamGetPoolsResponse


class TestRenderstreamGetPoolsResponse(unittest.TestCase):
    """RenderstreamGetPoolsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRenderstreamGetPoolsResponse(self):
        """Test RenderstreamGetPoolsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RenderstreamGetPoolsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
