"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.renderstream_workload_info import RenderstreamWorkloadInfo
globals()['RenderstreamWorkloadInfo'] = RenderstreamWorkloadInfo
from openapi_client.model.renderstream_list_workloads_response import RenderstreamListWorkloadsResponse


class TestRenderstreamListWorkloadsResponse(unittest.TestCase):
    """RenderstreamListWorkloadsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRenderstreamListWorkloadsResponse(self):
        """Test RenderstreamListWorkloadsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RenderstreamListWorkloadsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
