"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.content_resolution import ContentResolution


class TestContentResolution(unittest.TestCase):
    """ContentResolution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContentResolution(self):
        """Test ContentResolution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContentResolution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
