"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.track_info_crossfade_mode import TrackInfoCrossfadeMode
globals()['TrackInfoCrossfadeMode'] = TrackInfoCrossfadeMode
from openapi_client.model.transport_track_info import TransportTrackInfo


class TestTransportTrackInfo(unittest.TestCase):
    """TransportTrackInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransportTrackInfo(self):
        """Test TransportTrackInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransportTrackInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
