"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_mr_set_info import V1MRSetInfo
globals()['V1MRSetInfo'] = V1MRSetInfo
from openapi_client.model.v1_list_mr_sets_response import V1ListMRSetsResponse


class TestV1ListMRSetsResponse(unittest.TestCase):
    """V1ListMRSetsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ListMRSetsResponse(self):
        """Test V1ListMRSetsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1ListMRSetsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
