"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.mixedreality_camera_identity_info import MixedrealityCameraIdentityInfo
globals()['MixedrealityCameraIdentityInfo'] = MixedrealityCameraIdentityInfo
from openapi_client.model.mixedreality_mr_set import MixedrealityMRSet


class TestMixedrealityMRSet(unittest.TestCase):
    """MixedrealityMRSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMixedrealityMRSet(self):
        """Test MixedrealityMRSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MixedrealityMRSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
