"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cameracalibration_enable_observation_response import CameracalibrationEnableObservationResponse


class TestCameracalibrationEnableObservationResponse(unittest.TestCase):
    """CameracalibrationEnableObservationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCameracalibrationEnableObservationResponse(self):
        """Test CameracalibrationEnableObservationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CameracalibrationEnableObservationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
