"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.renderstream_clipping_region import RenderstreamClippingRegion
from openapi_client.model.stream_info_stream_status import StreamInfoStreamStatus
globals()['RenderstreamClippingRegion'] = RenderstreamClippingRegion
globals()['StreamInfoStreamStatus'] = StreamInfoStreamStatus
from openapi_client.model.renderstream_stream_info import RenderstreamStreamInfo


class TestRenderstreamStreamInfo(unittest.TestCase):
    """RenderstreamStreamInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRenderstreamStreamInfo(self):
        """Test RenderstreamStreamInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RenderstreamStreamInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
