"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.renderstream_reference_info import RenderstreamReferenceInfo


class TestRenderstreamReferenceInfo(unittest.TestCase):
    """RenderstreamReferenceInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRenderstreamReferenceInfo(self):
        """Test RenderstreamReferenceInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RenderstreamReferenceInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
