"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_camera_info import V1CameraInfo
globals()['V1CameraInfo'] = V1CameraInfo
from openapi_client.model.v1_mr_set_info import V1MRSetInfo


class TestV1MRSetInfo(unittest.TestCase):
    """V1MRSetInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1MRSetInfo(self):
        """Test V1MRSetInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1MRSetInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
