"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.rpc_status import RpcStatus
from openapi_client.model.sequencing_list_indirection_item import SequencingListIndirectionItem
globals()['RpcStatus'] = RpcStatus
globals()['SequencingListIndirectionItem'] = SequencingListIndirectionItem
from openapi_client.model.sequencing_list_indirections_response import SequencingListIndirectionsResponse


class TestSequencingListIndirectionsResponse(unittest.TestCase):
    """SequencingListIndirectionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSequencingListIndirectionsResponse(self):
        """Test SequencingListIndirectionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SequencingListIndirectionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
