"""
    d3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.thumbnails_api import ThumbnailsApi  # noqa: E501


class TestThumbnailsApi(unittest.TestCase):
    """ThumbnailsApi unit test stubs"""

    def setUp(self):
        self.api = ThumbnailsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_thumbnails_get_thumbnail(self):
        """Test case for thumbnails_get_thumbnail

        Get thumbnail for a resource  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
