/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIMixedrealityPose.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIMixedrealityPose::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Position.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("position")); WriteJsonValue(Writer, Position.GetValue());
	}
	if (Rotation.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rotation")); WriteJsonValue(Writer, Rotation.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIMixedrealityPose::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("position"), Position);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("rotation"), Rotation);

	return ParseSuccess;
}

}
