/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIRenderstreamListClustersResponse.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIRenderstreamListClustersResponse::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Clusters.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("clusters")); WriteJsonValue(Writer, Clusters.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIRenderstreamListClustersResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("clusters"), Clusters);

	return ParseSuccess;
}

}
