/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIContentResolution.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIContentResolution::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Width.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("width")); WriteJsonValue(Writer, Width.GetValue());
	}
	if (Height.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("height")); WriteJsonValue(Writer, Height.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIContentResolution::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("width"), Width);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("height"), Height);

	return ParseSuccess;
}

}
