/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIStatusGetProjectResult.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIStatusGetProjectResult::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (ProjectPath.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("projectPath")); WriteJsonValue(Writer, ProjectPath.GetValue());
	}
	if (Version.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("version")); WriteJsonValue(Writer, Version.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIStatusGetProjectResult::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("projectPath"), ProjectPath);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("version"), Version);

	return ParseSuccess;
}

}
