/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPID3apiVec2Float.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPID3apiVec2Float::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (X.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("x")); WriteJsonValue(Writer, X.GetValue());
	}
	if (Y.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("y")); WriteJsonValue(Writer, Y.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPID3apiVec2Float::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("x"), X);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("y"), Y);

	return ParseSuccess;
}

}
