/*
 * workload_instance_info_workload_instance_status.h
 *
 * 
 */

#ifndef _workload_instance_info_workload_instance_status_H_
#define _workload_instance_info_workload_instance_status_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct workload_instance_info_workload_instance_status_t workload_instance_info_workload_instance_status_t;


// Enum  for workload_instance_info_workload_instance_status

typedef enum { d3_api_workload_instance_info_workload_instance_status__NULL = 0, d3_api_workload_instance_info_workload_instance_status__UNKNOWN, d3_api_workload_instance_info_workload_instance_status__CRASHED, d3_api_workload_instance_info_workload_instance_status__ERROR, d3_api_workload_instance_info_workload_instance_status__STOPPING, d3_api_workload_instance_info_workload_instance_status__STOPPED, d3_api_workload_instance_info_workload_instance_status__LAUNCHING, d3_api_workload_instance_info_workload_instance_status__STARTING, d3_api_workload_instance_info_workload_instance_status__READY, d3_api_workload_instance_info_workload_instance_status__STANDBY, d3_api_workload_instance_info_workload_instance_status__RUNNING } d3_api_workload_instance_info_workload_instance_status__e;

char* workload_instance_info_workload_instance_status_workload_instance_info_workload_instance_status_ToString(d3_api_workload_instance_info_workload_instance_status__e workload_instance_info_workload_instance_status);

d3_api_workload_instance_info_workload_instance_status__e workload_instance_info_workload_instance_status_workload_instance_info_workload_instance_status_FromString(char* workload_instance_info_workload_instance_status);

//cJSON *workload_instance_info_workload_instance_status_workload_instance_info_workload_instance_status_convertToJSON(d3_api_workload_instance_info_workload_instance_status__e workload_instance_info_workload_instance_status);

//d3_api_workload_instance_info_workload_instance_status__e workload_instance_info_workload_instance_status_workload_instance_info_workload_instance_status_parseFromJSON(cJSON *workload_instance_info_workload_instance_statusJSON);

#endif /* _workload_instance_info_workload_instance_status_H_ */

