/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIContentResolution.h"

namespace OpenAPI
{

/*
 * OpenAPIContentImageMetadata
 *
 * 
 */
class OPENAPI_API OpenAPIContentImageMetadata : public Model
{
public:
    virtual ~OpenAPIContentImageMetadata() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIContentResolution> Resolution;
	TOptional<int64> BitsPerPixel;
	TOptional<FString> Codec;
	TOptional<bool> HasAlpha;
};

}
