/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIRpcStatus.h"

namespace OpenAPI
{

/*
 * OpenAPID3apiBoolResponse
 *
 * 
 */
class OPENAPI_API OpenAPID3apiBoolResponse : public Model
{
public:
    virtual ~OpenAPID3apiBoolResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIRpcStatus> Status;
	TOptional<bool> Result;
};

}
