/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIRenderstreamReferenceInfo.h"
#include "OpenAPIRenderstreamStreamInfo.h"
#include "OpenAPIRenderstreamWorkloadInfo.h"

namespace OpenAPI
{

/*
 * OpenAPIRenderstreamGetLayerStatusResult
 *
 * 
 */
class OPENAPI_API OpenAPIRenderstreamGetLayerStatusResult : public Model
{
public:
    virtual ~OpenAPIRenderstreamGetLayerStatusResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIRenderstreamReferenceInfo> Reference;
	TOptional<OpenAPIRenderstreamWorkloadInfo> Workload;
	TOptional<TArray<OpenAPIRenderstreamStreamInfo>> Streams;
	TOptional<TArray<FString>> AssetErrors;
};

}
