/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIRenderstreamWorkloadInfo.h"

namespace OpenAPI
{

/*
 * OpenAPIRenderstreamGetWorkloadResponse
 *
 * 
 */
class OPENAPI_API OpenAPIRenderstreamGetWorkloadResponse : public Model
{
public:
    virtual ~OpenAPIRenderstreamGetWorkloadResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIRenderstreamWorkloadInfo> Result;
};

}
