/**
 * d3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIRenderstreamNetworkInfo.h"
#include "OpenAPIRenderstreamTransportInfo.h"

namespace OpenAPI
{

/*
 * OpenAPIRenderstreamAssignerInfo
 *
 * 
 */
class OPENAPI_API OpenAPIRenderstreamAssignerInfo : public Model
{
public:
    virtual ~OpenAPIRenderstreamAssignerInfo() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> Uid;
	TOptional<FString> Name;
	TOptional<OpenAPIRenderstreamTransportInfo> Transport;
	TOptional<bool> Alpha;
	TOptional<int32> OverlapPixels;
	TOptional<int32> PaddingPixels;
	TOptional<OpenAPIRenderstreamNetworkInfo> PreferredNetwork;
};

}
