/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransportStopRequest struct for TransportStopRequest
type TransportStopRequest struct {
	Transports *[]D3apiLocator `json:"transports,omitempty"`
}

// NewTransportStopRequest instantiates a new TransportStopRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportStopRequest() *TransportStopRequest {
	this := TransportStopRequest{}
	return &this
}

// NewTransportStopRequestWithDefaults instantiates a new TransportStopRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportStopRequestWithDefaults() *TransportStopRequest {
	this := TransportStopRequest{}
	return &this
}

// GetTransports returns the Transports field value if set, zero value otherwise.
func (o *TransportStopRequest) GetTransports() []D3apiLocator {
	if o == nil || o.Transports == nil {
		var ret []D3apiLocator
		return ret
	}
	return *o.Transports
}

// GetTransportsOk returns a tuple with the Transports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportStopRequest) GetTransportsOk() (*[]D3apiLocator, bool) {
	if o == nil || o.Transports == nil {
		return nil, false
	}
	return o.Transports, true
}

// HasTransports returns a boolean if a field has been set.
func (o *TransportStopRequest) HasTransports() bool {
	if o != nil && o.Transports != nil {
		return true
	}

	return false
}

// SetTransports gets a reference to the given []D3apiLocator and assigns it to the Transports field.
func (o *TransportStopRequest) SetTransports(v []D3apiLocator) {
	o.Transports = &v
}

func (o TransportStopRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Transports != nil {
		toSerialize["transports"] = o.Transports
	}
	return json.Marshal(toSerialize)
}

type NullableTransportStopRequest struct {
	value *TransportStopRequest
	isSet bool
}

func (v NullableTransportStopRequest) Get() *TransportStopRequest {
	return v.value
}

func (v *NullableTransportStopRequest) Set(val *TransportStopRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportStopRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportStopRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportStopRequest(val *TransportStopRequest) *NullableTransportStopRequest {
	return &NullableTransportStopRequest{value: val, isSet: true}
}

func (v NullableTransportStopRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportStopRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


