/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RenderstreamGetWorkloadInstanceResponse struct for RenderstreamGetWorkloadInstanceResponse
type RenderstreamGetWorkloadInstanceResponse struct {
	Result *RenderstreamWorkloadInstanceInfo `json:"result,omitempty"`
}

// NewRenderstreamGetWorkloadInstanceResponse instantiates a new RenderstreamGetWorkloadInstanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderstreamGetWorkloadInstanceResponse() *RenderstreamGetWorkloadInstanceResponse {
	this := RenderstreamGetWorkloadInstanceResponse{}
	return &this
}

// NewRenderstreamGetWorkloadInstanceResponseWithDefaults instantiates a new RenderstreamGetWorkloadInstanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderstreamGetWorkloadInstanceResponseWithDefaults() *RenderstreamGetWorkloadInstanceResponse {
	this := RenderstreamGetWorkloadInstanceResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *RenderstreamGetWorkloadInstanceResponse) GetResult() RenderstreamWorkloadInstanceInfo {
	if o == nil || o.Result == nil {
		var ret RenderstreamWorkloadInstanceInfo
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderstreamGetWorkloadInstanceResponse) GetResultOk() (*RenderstreamWorkloadInstanceInfo, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *RenderstreamGetWorkloadInstanceResponse) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given RenderstreamWorkloadInstanceInfo and assigns it to the Result field.
func (o *RenderstreamGetWorkloadInstanceResponse) SetResult(v RenderstreamWorkloadInstanceInfo) {
	o.Result = &v
}

func (o RenderstreamGetWorkloadInstanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableRenderstreamGetWorkloadInstanceResponse struct {
	value *RenderstreamGetWorkloadInstanceResponse
	isSet bool
}

func (v NullableRenderstreamGetWorkloadInstanceResponse) Get() *RenderstreamGetWorkloadInstanceResponse {
	return v.value
}

func (v *NullableRenderstreamGetWorkloadInstanceResponse) Set(val *RenderstreamGetWorkloadInstanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderstreamGetWorkloadInstanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderstreamGetWorkloadInstanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderstreamGetWorkloadInstanceResponse(val *RenderstreamGetWorkloadInstanceResponse) *NullableRenderstreamGetWorkloadInstanceResponse {
	return &NullableRenderstreamGetWorkloadInstanceResponse{value: val, isSet: true}
}

func (v NullableRenderstreamGetWorkloadInstanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderstreamGetWorkloadInstanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


