/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransportGoToNoteRequest struct for TransportGoToNoteRequest
type TransportGoToNoteRequest struct {
	Transports *[]TransportGotoNoteInfo `json:"transports,omitempty"`
}

// NewTransportGoToNoteRequest instantiates a new TransportGoToNoteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportGoToNoteRequest() *TransportGoToNoteRequest {
	this := TransportGoToNoteRequest{}
	return &this
}

// NewTransportGoToNoteRequestWithDefaults instantiates a new TransportGoToNoteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportGoToNoteRequestWithDefaults() *TransportGoToNoteRequest {
	this := TransportGoToNoteRequest{}
	return &this
}

// GetTransports returns the Transports field value if set, zero value otherwise.
func (o *TransportGoToNoteRequest) GetTransports() []TransportGotoNoteInfo {
	if o == nil || o.Transports == nil {
		var ret []TransportGotoNoteInfo
		return ret
	}
	return *o.Transports
}

// GetTransportsOk returns a tuple with the Transports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportGoToNoteRequest) GetTransportsOk() (*[]TransportGotoNoteInfo, bool) {
	if o == nil || o.Transports == nil {
		return nil, false
	}
	return o.Transports, true
}

// HasTransports returns a boolean if a field has been set.
func (o *TransportGoToNoteRequest) HasTransports() bool {
	if o != nil && o.Transports != nil {
		return true
	}

	return false
}

// SetTransports gets a reference to the given []TransportGotoNoteInfo and assigns it to the Transports field.
func (o *TransportGoToNoteRequest) SetTransports(v []TransportGotoNoteInfo) {
	o.Transports = &v
}

func (o TransportGoToNoteRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Transports != nil {
		toSerialize["transports"] = o.Transports
	}
	return json.Marshal(toSerialize)
}

type NullableTransportGoToNoteRequest struct {
	value *TransportGoToNoteRequest
	isSet bool
}

func (v NullableTransportGoToNoteRequest) Get() *TransportGoToNoteRequest {
	return v.value
}

func (v *NullableTransportGoToNoteRequest) Set(val *TransportGoToNoteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportGoToNoteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportGoToNoteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportGoToNoteRequest(val *TransportGoToNoteRequest) *NullableTransportGoToNoteRequest {
	return &NullableTransportGoToNoteRequest{value: val, isSet: true}
}

func (v NullableTransportGoToNoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportGoToNoteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


