/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CameracalibrationCameraInfo struct for CameracalibrationCameraInfo
type CameracalibrationCameraInfo struct {
	Uid *string `json:"uid,omitempty"`
	Name *string `json:"name,omitempty"`
	Observations *[]CameracalibrationObservationInfo `json:"observations,omitempty"`
}

// NewCameracalibrationCameraInfo instantiates a new CameracalibrationCameraInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCameracalibrationCameraInfo() *CameracalibrationCameraInfo {
	this := CameracalibrationCameraInfo{}
	return &this
}

// NewCameracalibrationCameraInfoWithDefaults instantiates a new CameracalibrationCameraInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCameracalibrationCameraInfoWithDefaults() *CameracalibrationCameraInfo {
	this := CameracalibrationCameraInfo{}
	return &this
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *CameracalibrationCameraInfo) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CameracalibrationCameraInfo) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *CameracalibrationCameraInfo) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *CameracalibrationCameraInfo) SetUid(v string) {
	o.Uid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CameracalibrationCameraInfo) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CameracalibrationCameraInfo) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CameracalibrationCameraInfo) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CameracalibrationCameraInfo) SetName(v string) {
	o.Name = &v
}

// GetObservations returns the Observations field value if set, zero value otherwise.
func (o *CameracalibrationCameraInfo) GetObservations() []CameracalibrationObservationInfo {
	if o == nil || o.Observations == nil {
		var ret []CameracalibrationObservationInfo
		return ret
	}
	return *o.Observations
}

// GetObservationsOk returns a tuple with the Observations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CameracalibrationCameraInfo) GetObservationsOk() (*[]CameracalibrationObservationInfo, bool) {
	if o == nil || o.Observations == nil {
		return nil, false
	}
	return o.Observations, true
}

// HasObservations returns a boolean if a field has been set.
func (o *CameracalibrationCameraInfo) HasObservations() bool {
	if o != nil && o.Observations != nil {
		return true
	}

	return false
}

// SetObservations gets a reference to the given []CameracalibrationObservationInfo and assigns it to the Observations field.
func (o *CameracalibrationCameraInfo) SetObservations(v []CameracalibrationObservationInfo) {
	o.Observations = &v
}

func (o CameracalibrationCameraInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Observations != nil {
		toSerialize["observations"] = o.Observations
	}
	return json.Marshal(toSerialize)
}

type NullableCameracalibrationCameraInfo struct {
	value *CameracalibrationCameraInfo
	isSet bool
}

func (v NullableCameracalibrationCameraInfo) Get() *CameracalibrationCameraInfo {
	return v.value
}

func (v *NullableCameracalibrationCameraInfo) Set(val *CameracalibrationCameraInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCameracalibrationCameraInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCameracalibrationCameraInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCameracalibrationCameraInfo(val *CameracalibrationCameraInfo) *NullableCameracalibrationCameraInfo {
	return &NullableCameracalibrationCameraInfo{value: val, isSet: true}
}

func (v NullableCameracalibrationCameraInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCameracalibrationCameraInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


