/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// QuickcalListReferencePointsResponse struct for QuickcalListReferencePointsResponse
type QuickcalListReferencePointsResponse struct {
	Status *RpcStatus `json:"status,omitempty"`
	Result *[]QuickcalReferencePointInfo `json:"result,omitempty"`
}

// NewQuickcalListReferencePointsResponse instantiates a new QuickcalListReferencePointsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuickcalListReferencePointsResponse() *QuickcalListReferencePointsResponse {
	this := QuickcalListReferencePointsResponse{}
	return &this
}

// NewQuickcalListReferencePointsResponseWithDefaults instantiates a new QuickcalListReferencePointsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuickcalListReferencePointsResponseWithDefaults() *QuickcalListReferencePointsResponse {
	this := QuickcalListReferencePointsResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *QuickcalListReferencePointsResponse) GetStatus() RpcStatus {
	if o == nil || o.Status == nil {
		var ret RpcStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickcalListReferencePointsResponse) GetStatusOk() (*RpcStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *QuickcalListReferencePointsResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RpcStatus and assigns it to the Status field.
func (o *QuickcalListReferencePointsResponse) SetStatus(v RpcStatus) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *QuickcalListReferencePointsResponse) GetResult() []QuickcalReferencePointInfo {
	if o == nil || o.Result == nil {
		var ret []QuickcalReferencePointInfo
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickcalListReferencePointsResponse) GetResultOk() (*[]QuickcalReferencePointInfo, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *QuickcalListReferencePointsResponse) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given []QuickcalReferencePointInfo and assigns it to the Result field.
func (o *QuickcalListReferencePointsResponse) SetResult(v []QuickcalReferencePointInfo) {
	o.Result = &v
}

func (o QuickcalListReferencePointsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableQuickcalListReferencePointsResponse struct {
	value *QuickcalListReferencePointsResponse
	isSet bool
}

func (v NullableQuickcalListReferencePointsResponse) Get() *QuickcalListReferencePointsResponse {
	return v.value
}

func (v *NullableQuickcalListReferencePointsResponse) Set(val *QuickcalListReferencePointsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQuickcalListReferencePointsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQuickcalListReferencePointsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuickcalListReferencePointsResponse(val *QuickcalListReferencePointsResponse) *NullableQuickcalListReferencePointsResponse {
	return &NullableQuickcalListReferencePointsResponse{value: val, isSet: true}
}

func (v NullableQuickcalListReferencePointsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuickcalListReferencePointsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


