/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Statusd3Machine struct for Statusd3Machine
type Statusd3Machine struct {
	Uid *string `json:"uid,omitempty"`
	Name *string `json:"name,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
}

// NewStatusd3Machine instantiates a new Statusd3Machine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusd3Machine() *Statusd3Machine {
	this := Statusd3Machine{}
	return &this
}

// NewStatusd3MachineWithDefaults instantiates a new Statusd3Machine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusd3MachineWithDefaults() *Statusd3Machine {
	this := Statusd3Machine{}
	return &this
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *Statusd3Machine) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Statusd3Machine) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *Statusd3Machine) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *Statusd3Machine) SetUid(v string) {
	o.Uid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Statusd3Machine) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Statusd3Machine) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Statusd3Machine) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Statusd3Machine) SetName(v string) {
	o.Name = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *Statusd3Machine) GetHostname() string {
	if o == nil || o.Hostname == nil {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Statusd3Machine) GetHostnameOk() (*string, bool) {
	if o == nil || o.Hostname == nil {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *Statusd3Machine) HasHostname() bool {
	if o != nil && o.Hostname != nil {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *Statusd3Machine) SetHostname(v string) {
	o.Hostname = &v
}

func (o Statusd3Machine) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Hostname != nil {
		toSerialize["hostname"] = o.Hostname
	}
	return json.Marshal(toSerialize)
}

type NullableStatusd3Machine struct {
	value *Statusd3Machine
	isSet bool
}

func (v NullableStatusd3Machine) Get() *Statusd3Machine {
	return v.value
}

func (v *NullableStatusd3Machine) Set(val *Statusd3Machine) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusd3Machine) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusd3Machine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusd3Machine(val *Statusd3Machine) *NullableStatusd3Machine {
	return &NullableStatusd3Machine{value: val, isSet: true}
}

func (v NullableStatusd3Machine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusd3Machine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


