/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// QuickcalReferencePointInfo struct for QuickcalReferencePointInfo
type QuickcalReferencePointInfo struct {
	Uid *string `json:"uid,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewQuickcalReferencePointInfo instantiates a new QuickcalReferencePointInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuickcalReferencePointInfo() *QuickcalReferencePointInfo {
	this := QuickcalReferencePointInfo{}
	return &this
}

// NewQuickcalReferencePointInfoWithDefaults instantiates a new QuickcalReferencePointInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuickcalReferencePointInfoWithDefaults() *QuickcalReferencePointInfo {
	this := QuickcalReferencePointInfo{}
	return &this
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *QuickcalReferencePointInfo) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickcalReferencePointInfo) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *QuickcalReferencePointInfo) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *QuickcalReferencePointInfo) SetUid(v string) {
	o.Uid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *QuickcalReferencePointInfo) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickcalReferencePointInfo) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *QuickcalReferencePointInfo) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *QuickcalReferencePointInfo) SetName(v string) {
	o.Name = &v
}

func (o QuickcalReferencePointInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableQuickcalReferencePointInfo struct {
	value *QuickcalReferencePointInfo
	isSet bool
}

func (v NullableQuickcalReferencePointInfo) Get() *QuickcalReferencePointInfo {
	return v.value
}

func (v *NullableQuickcalReferencePointInfo) Set(val *QuickcalReferencePointInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableQuickcalReferencePointInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableQuickcalReferencePointInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuickcalReferencePointInfo(val *QuickcalReferencePointInfo) *NullableQuickcalReferencePointInfo {
	return &NullableQuickcalReferencePointInfo{value: val, isSet: true}
}

func (v NullableQuickcalReferencePointInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuickcalReferencePointInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


