/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransportSetVolumeInfo struct for TransportSetVolumeInfo
type TransportSetVolumeInfo struct {
	Transport *D3apiLocator `json:"transport,omitempty"`
	Volume *float64 `json:"volume,omitempty"`
}

// NewTransportSetVolumeInfo instantiates a new TransportSetVolumeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportSetVolumeInfo() *TransportSetVolumeInfo {
	this := TransportSetVolumeInfo{}
	return &this
}

// NewTransportSetVolumeInfoWithDefaults instantiates a new TransportSetVolumeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportSetVolumeInfoWithDefaults() *TransportSetVolumeInfo {
	this := TransportSetVolumeInfo{}
	return &this
}

// GetTransport returns the Transport field value if set, zero value otherwise.
func (o *TransportSetVolumeInfo) GetTransport() D3apiLocator {
	if o == nil || o.Transport == nil {
		var ret D3apiLocator
		return ret
	}
	return *o.Transport
}

// GetTransportOk returns a tuple with the Transport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportSetVolumeInfo) GetTransportOk() (*D3apiLocator, bool) {
	if o == nil || o.Transport == nil {
		return nil, false
	}
	return o.Transport, true
}

// HasTransport returns a boolean if a field has been set.
func (o *TransportSetVolumeInfo) HasTransport() bool {
	if o != nil && o.Transport != nil {
		return true
	}

	return false
}

// SetTransport gets a reference to the given D3apiLocator and assigns it to the Transport field.
func (o *TransportSetVolumeInfo) SetTransport(v D3apiLocator) {
	o.Transport = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *TransportSetVolumeInfo) GetVolume() float64 {
	if o == nil || o.Volume == nil {
		var ret float64
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportSetVolumeInfo) GetVolumeOk() (*float64, bool) {
	if o == nil || o.Volume == nil {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *TransportSetVolumeInfo) HasVolume() bool {
	if o != nil && o.Volume != nil {
		return true
	}

	return false
}

// SetVolume gets a reference to the given float64 and assigns it to the Volume field.
func (o *TransportSetVolumeInfo) SetVolume(v float64) {
	o.Volume = &v
}

func (o TransportSetVolumeInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Transport != nil {
		toSerialize["transport"] = o.Transport
	}
	if o.Volume != nil {
		toSerialize["volume"] = o.Volume
	}
	return json.Marshal(toSerialize)
}

type NullableTransportSetVolumeInfo struct {
	value *TransportSetVolumeInfo
	isSet bool
}

func (v NullableTransportSetVolumeInfo) Get() *TransportSetVolumeInfo {
	return v.value
}

func (v *NullableTransportSetVolumeInfo) Set(val *TransportSetVolumeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportSetVolumeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportSetVolumeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportSetVolumeInfo(val *TransportSetVolumeInfo) *NullableTransportSetVolumeInfo {
	return &NullableTransportSetVolumeInfo{value: val, isSet: true}
}

func (v NullableTransportSetVolumeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportSetVolumeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


