/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StatusGetProjectResponse struct for StatusGetProjectResponse
type StatusGetProjectResponse struct {
	Status *RpcStatus `json:"status,omitempty"`
	Result *StatusGetProjectResult `json:"result,omitempty"`
}

// NewStatusGetProjectResponse instantiates a new StatusGetProjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusGetProjectResponse() *StatusGetProjectResponse {
	this := StatusGetProjectResponse{}
	return &this
}

// NewStatusGetProjectResponseWithDefaults instantiates a new StatusGetProjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusGetProjectResponseWithDefaults() *StatusGetProjectResponse {
	this := StatusGetProjectResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *StatusGetProjectResponse) GetStatus() RpcStatus {
	if o == nil || o.Status == nil {
		var ret RpcStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatusGetProjectResponse) GetStatusOk() (*RpcStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *StatusGetProjectResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RpcStatus and assigns it to the Status field.
func (o *StatusGetProjectResponse) SetStatus(v RpcStatus) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *StatusGetProjectResponse) GetResult() StatusGetProjectResult {
	if o == nil || o.Result == nil {
		var ret StatusGetProjectResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatusGetProjectResponse) GetResultOk() (*StatusGetProjectResult, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *StatusGetProjectResponse) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given StatusGetProjectResult and assigns it to the Result field.
func (o *StatusGetProjectResponse) SetResult(v StatusGetProjectResult) {
	o.Result = &v
}

func (o StatusGetProjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableStatusGetProjectResponse struct {
	value *StatusGetProjectResponse
	isSet bool
}

func (v NullableStatusGetProjectResponse) Get() *StatusGetProjectResponse {
	return v.value
}

func (v *NullableStatusGetProjectResponse) Set(val *StatusGetProjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusGetProjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusGetProjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusGetProjectResponse(val *StatusGetProjectResponse) *NullableStatusGetProjectResponse {
	return &NullableStatusGetProjectResponse{value: val, isSet: true}
}

func (v NullableStatusGetProjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusGetProjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


