/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RenderstreamRenderStreamInfo struct for RenderstreamRenderStreamInfo
type RenderstreamRenderStreamInfo struct {
	Uid *string `json:"uid,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewRenderstreamRenderStreamInfo instantiates a new RenderstreamRenderStreamInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderstreamRenderStreamInfo() *RenderstreamRenderStreamInfo {
	this := RenderstreamRenderStreamInfo{}
	return &this
}

// NewRenderstreamRenderStreamInfoWithDefaults instantiates a new RenderstreamRenderStreamInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderstreamRenderStreamInfoWithDefaults() *RenderstreamRenderStreamInfo {
	this := RenderstreamRenderStreamInfo{}
	return &this
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *RenderstreamRenderStreamInfo) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderstreamRenderStreamInfo) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *RenderstreamRenderStreamInfo) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *RenderstreamRenderStreamInfo) SetUid(v string) {
	o.Uid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RenderstreamRenderStreamInfo) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderstreamRenderStreamInfo) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RenderstreamRenderStreamInfo) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RenderstreamRenderStreamInfo) SetName(v string) {
	o.Name = &v
}

func (o RenderstreamRenderStreamInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableRenderstreamRenderStreamInfo struct {
	value *RenderstreamRenderStreamInfo
	isSet bool
}

func (v NullableRenderstreamRenderStreamInfo) Get() *RenderstreamRenderStreamInfo {
	return v.value
}

func (v *NullableRenderstreamRenderStreamInfo) Set(val *RenderstreamRenderStreamInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderstreamRenderStreamInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderstreamRenderStreamInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderstreamRenderStreamInfo(val *RenderstreamRenderStreamInfo) *NullableRenderstreamRenderStreamInfo {
	return &NullableRenderstreamRenderStreamInfo{value: val, isSet: true}
}

func (v NullableRenderstreamRenderStreamInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderstreamRenderStreamInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


