/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StatusGetSessionResponse struct for StatusGetSessionResponse
type StatusGetSessionResponse struct {
	Status *RpcStatus `json:"status,omitempty"`
	Result *StatusGetSessionResult `json:"result,omitempty"`
}

// NewStatusGetSessionResponse instantiates a new StatusGetSessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusGetSessionResponse() *StatusGetSessionResponse {
	this := StatusGetSessionResponse{}
	return &this
}

// NewStatusGetSessionResponseWithDefaults instantiates a new StatusGetSessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusGetSessionResponseWithDefaults() *StatusGetSessionResponse {
	this := StatusGetSessionResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *StatusGetSessionResponse) GetStatus() RpcStatus {
	if o == nil || o.Status == nil {
		var ret RpcStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatusGetSessionResponse) GetStatusOk() (*RpcStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *StatusGetSessionResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RpcStatus and assigns it to the Status field.
func (o *StatusGetSessionResponse) SetStatus(v RpcStatus) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *StatusGetSessionResponse) GetResult() StatusGetSessionResult {
	if o == nil || o.Result == nil {
		var ret StatusGetSessionResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatusGetSessionResponse) GetResultOk() (*StatusGetSessionResult, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *StatusGetSessionResponse) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given StatusGetSessionResult and assigns it to the Result field.
func (o *StatusGetSessionResponse) SetResult(v StatusGetSessionResult) {
	o.Result = &v
}

func (o StatusGetSessionResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableStatusGetSessionResponse struct {
	value *StatusGetSessionResponse
	isSet bool
}

func (v NullableStatusGetSessionResponse) Get() *StatusGetSessionResponse {
	return v.value
}

func (v *NullableStatusGetSessionResponse) Set(val *StatusGetSessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusGetSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusGetSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusGetSessionResponse(val *StatusGetSessionResponse) *NullableStatusGetSessionResponse {
	return &NullableStatusGetSessionResponse{value: val, isSet: true}
}

func (v NullableStatusGetSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusGetSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


