/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CameracalibrationFloat3 struct for CameracalibrationFloat3
type CameracalibrationFloat3 struct {
	X *float32 `json:"x,omitempty"`
	Y *float32 `json:"y,omitempty"`
	Z *float32 `json:"z,omitempty"`
}

// NewCameracalibrationFloat3 instantiates a new CameracalibrationFloat3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCameracalibrationFloat3() *CameracalibrationFloat3 {
	this := CameracalibrationFloat3{}
	return &this
}

// NewCameracalibrationFloat3WithDefaults instantiates a new CameracalibrationFloat3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCameracalibrationFloat3WithDefaults() *CameracalibrationFloat3 {
	this := CameracalibrationFloat3{}
	return &this
}

// GetX returns the X field value if set, zero value otherwise.
func (o *CameracalibrationFloat3) GetX() float32 {
	if o == nil || o.X == nil {
		var ret float32
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CameracalibrationFloat3) GetXOk() (*float32, bool) {
	if o == nil || o.X == nil {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *CameracalibrationFloat3) HasX() bool {
	if o != nil && o.X != nil {
		return true
	}

	return false
}

// SetX gets a reference to the given float32 and assigns it to the X field.
func (o *CameracalibrationFloat3) SetX(v float32) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *CameracalibrationFloat3) GetY() float32 {
	if o == nil || o.Y == nil {
		var ret float32
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CameracalibrationFloat3) GetYOk() (*float32, bool) {
	if o == nil || o.Y == nil {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *CameracalibrationFloat3) HasY() bool {
	if o != nil && o.Y != nil {
		return true
	}

	return false
}

// SetY gets a reference to the given float32 and assigns it to the Y field.
func (o *CameracalibrationFloat3) SetY(v float32) {
	o.Y = &v
}

// GetZ returns the Z field value if set, zero value otherwise.
func (o *CameracalibrationFloat3) GetZ() float32 {
	if o == nil || o.Z == nil {
		var ret float32
		return ret
	}
	return *o.Z
}

// GetZOk returns a tuple with the Z field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CameracalibrationFloat3) GetZOk() (*float32, bool) {
	if o == nil || o.Z == nil {
		return nil, false
	}
	return o.Z, true
}

// HasZ returns a boolean if a field has been set.
func (o *CameracalibrationFloat3) HasZ() bool {
	if o != nil && o.Z != nil {
		return true
	}

	return false
}

// SetZ gets a reference to the given float32 and assigns it to the Z field.
func (o *CameracalibrationFloat3) SetZ(v float32) {
	o.Z = &v
}

func (o CameracalibrationFloat3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.X != nil {
		toSerialize["x"] = o.X
	}
	if o.Y != nil {
		toSerialize["y"] = o.Y
	}
	if o.Z != nil {
		toSerialize["z"] = o.Z
	}
	return json.Marshal(toSerialize)
}

type NullableCameracalibrationFloat3 struct {
	value *CameracalibrationFloat3
	isSet bool
}

func (v NullableCameracalibrationFloat3) Get() *CameracalibrationFloat3 {
	return v.value
}

func (v *NullableCameracalibrationFloat3) Set(val *CameracalibrationFloat3) {
	v.value = val
	v.isSet = true
}

func (v NullableCameracalibrationFloat3) IsSet() bool {
	return v.isSet
}

func (v *NullableCameracalibrationFloat3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCameracalibrationFloat3(val *CameracalibrationFloat3) *NullableCameracalibrationFloat3 {
	return &NullableCameracalibrationFloat3{value: val, isSet: true}
}

func (v NullableCameracalibrationFloat3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCameracalibrationFloat3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


