/*
d3 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// D3apiBoolResponse struct for D3apiBoolResponse
type D3apiBoolResponse struct {
	Status *RpcStatus `json:"status,omitempty"`
	Result *bool `json:"result,omitempty"`
}

// NewD3apiBoolResponse instantiates a new D3apiBoolResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewD3apiBoolResponse() *D3apiBoolResponse {
	this := D3apiBoolResponse{}
	return &this
}

// NewD3apiBoolResponseWithDefaults instantiates a new D3apiBoolResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewD3apiBoolResponseWithDefaults() *D3apiBoolResponse {
	this := D3apiBoolResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *D3apiBoolResponse) GetStatus() RpcStatus {
	if o == nil || o.Status == nil {
		var ret RpcStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *D3apiBoolResponse) GetStatusOk() (*RpcStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *D3apiBoolResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RpcStatus and assigns it to the Status field.
func (o *D3apiBoolResponse) SetStatus(v RpcStatus) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *D3apiBoolResponse) GetResult() bool {
	if o == nil || o.Result == nil {
		var ret bool
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *D3apiBoolResponse) GetResultOk() (*bool, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *D3apiBoolResponse) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given bool and assigns it to the Result field.
func (o *D3apiBoolResponse) SetResult(v bool) {
	o.Result = &v
}

func (o D3apiBoolResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableD3apiBoolResponse struct {
	value *D3apiBoolResponse
	isSet bool
}

func (v NullableD3apiBoolResponse) Get() *D3apiBoolResponse {
	return v.value
}

func (v *NullableD3apiBoolResponse) Set(val *D3apiBoolResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableD3apiBoolResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableD3apiBoolResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableD3apiBoolResponse(val *D3apiBoolResponse) *NullableD3apiBoolResponse {
	return &NullableD3apiBoolResponse{value: val, isSet: true}
}

func (v NullableD3apiBoolResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableD3apiBoolResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


